[package]
name = "image-transfer"
version = "0.1.0"
authors = ["Julio <julioballista@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
question = "0.2.1"
structopt = "0.3.13"

